avoid exception on None object #6
File "/contrail-test/fixtures/k8s/namespace.py", line 54, in verify_on_setup if not self.verify_namespace_in_kube_manager():
File "tcutils/util.py", line 73, in f_retry result = f(*args, **kwargs) # first attempt
File "/contrail-test/fixtures/k8s/namespace.py", line 124, in verify_namespace_in_kube_manager
   self.namespace_info = km_h.get_namespace_info(ns_uuid = self.uuid)
AttributeError: 'NoneType' object has no attribute 'get_namespace_info'

add retries for get_kubemanager_h

Depends-On: I3e5d9edf14668a3aa6422cf4e40a64c4684b4bf3
Change-Id: I1bbc05d7cfbae743733d50fdec8ede3e01bb1c86
(cherry picked from commit 76e09c05e4ff5246891b9d41f2ff95502f0dd231)